name: contract_requiring_verification_published

on:
  repository_dispatch:
    types:
      - contract_requiring_verification_published

env:
  PACT_BROKER_BASE_URL: https://cd-dayn-upgrade.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  GIT_COMMIT: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  PACT_URL: ${{ github.event.client_payload.pact_url }}

jobs:
  verify-changed-pact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.14.1'
      - name: Build
        run: GIT_BRANCH=${GITHUB_REF:11} make ci_webhook
